const POST_READY_NOTIFICATION_TYPE_ID = 1;
const FOLLOW_REQUEST_NOTIFICATION_TYPE_ID = 2;
const FOLLOW_ACCEPT_NOTIFICATION_TYPE_ID = 3;


module.exports = {
  POST_READY_NOTIFICATION_TYPE_ID,
  FOLLOW_REQUEST_NOTIFICATION_TYPE_ID,
  FOLLOW_ACCEPT_NOTIFICATION_TYPE_ID,  
};