name: Remote Staging Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create Environment File
        run: |
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> staging.env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> staging.env
          echo "PORT=${{ secrets.PORT }}" >> staging.env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> staging.env
          echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> staging.env
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> staging.env
          echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> staging.env
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> staging.env
          echo "MYSQL_DB_PORT=${{ secrets.MYSQL_DB_PORT }}" >> staging.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> staging.env
          echo "bbdevcomVideo_ACCESS_TOKEN_ID=${{ secrets.bbdevcomVideo_ACCESS_TOKEN_ID }}" >> staging.env
          echo "bbdevcomVideo_SECRET_KEY=${{ secrets.bbdevcomVideo_SECRET_KEY }}" >> staging.env
          echo "MY_bbdevcomVideo_HOOK_KEY=${{ secrets.MY_bbdevcomVideo_HOOK_KEY }}" >> staging.env

      - name: Build Docker Image
        run: docker build -f dockerfiles/node.dockerfile -t odox700/org-ydotcom-be:staging-3.0 .

      - name: Push image to docker hub
        run: docker push odox700/org-ydotcom-be:staging-3.0

  deploy:
    needs: build
    runs-on: MyRandomOrganization-Runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set docker user permissions
        run: |
          sudo usermod -aG docker $USER
          newgrp docker
          sudo chmod 777 /var/run/docker.sock

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull image from docker hub
        run: docker pull odox700/org-ydotcom-be:staging-3.0

      - name: Delete old container
        run: docker rm -f ydotcombe

      - name: Run Docker Container
        run: |
          docker run -d \
          -p 380:80 \
          --name ydotcombe \
          odox700/org-ydotcom-be:staging-3.0
